name: counton
version: 0.1.0
synopsis: A benchmark-suite for counting, sorting, and reading
maintainer: Christian Gram Kalhauge <christian@kalhauge.dk>
github: kalhauge/counton
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - containers
  - contravariant
  - criterion
  - deepseq
  - discrimination
  - hashable
  - primitive
  - unordered-containers
  - vector
  - vector-hashtables


library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

benchmarks:
  main:
    main: Main.hs
    source-dirs: benchmark
    dependencies:
      - counton
    verbatim:
      default-language: GHC2021
